version: '3.8'

services:
  # Redis for the central server
  redis:
    image: redis:7-alpine
    container_name: llmama-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # LLMama Central Server
  llmama-server:
    build:
      context: ./server
      dockerfile: ../Dockerfile
    container_name: llmama-server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_ID=docker-server-001
      - LOG_LEVEL=info
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./server/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Example Worker Client (requires Ollama on host)
  # llmama-worker:
  #   build: .
  #   container_name: llmama-worker-001
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3000
  #     - WORKER_ID=docker-worker-001
  #     - SERVER_HOST=llmama-server
  #     - SERVER_PORT=4000
  #     - SERVER_REDIS_HOST=redis
  #     - SERVER_REDIS_PORT=6379
  #     - OLLAMA_HOST=host.docker.internal  # Assumes Ollama running on host
  #     - OLLAMA_PORT=11434
  #     - LOG_LEVEL=info
  #   depends_on:
  #     llmama-server:
  #       condition: service_healthy
  #   volumes:
  #     - ./logs:/app/logs
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

volumes:
  redis_data:
